export const cricData = {
  scoreCard: [
    {
      matchId: 43126,
      inningsId: 1,
      timeScore: 1667119467000,
      batTeamDetails: {
        batTeamId: 24,
        batTeamName: "Netherlands",
        batTeamShortName: "NED",
        batsmenData: {
          bat_5: {
            batId: 9725,
            batName: "Ackermann",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 27,
            balls: 27,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 100,
            outDesc: "lbw       b Shadab Khan",
            bowlerId: 11186,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 0,
            wicketCode: "LBW",
          },
          bat_2: {
            batId: 10424,
            batName: "Max ODowd",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 8,
            balls: 13,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 61.54,
            outDesc: "lbw       b Shadab Khan",
            bowlerId: 11186,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "LBW",
          },
          bat_10: {
            batId: 12783,
            batName: "Fred Klaassen",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 1,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "       b Mohammad Wasim Jr",
            bowlerId: 15040,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "BOWLED",
          },
          bat_7: {
            batId: 1669,
            batName: "van der Merwe",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 5,
            balls: 6,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 83.33,
            outDesc: "       b Haris Rauf",
            bowlerId: 14561,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "BOWLED",
          },
          bat_1: {
            batId: 8073,
            batName: "Myburgh",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 6,
            balls: 11,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 54.55,
            outDesc: "c Mohammad Wasim Jr       b Shaheen Afridi",
            bowlerId: 12160,
            fielderId1: 15040,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_8: {
            batId: 15205,
            batName: "Tim Pringle",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 5,
            balls: 8,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 62.5,
            outDesc: "       b Mohammad Wasim Jr",
            bowlerId: 15040,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "BOWLED",
          },
          bat_3: {
            batId: 13273,
            batName: "Bas de Leede",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 6,
            balls: 16,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 37.5,
            outDesc: "retd hurt",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "RETD_HURT",
          },
          bat_12: {
            batId: 15121,
            batName: "Brandon Glover",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_9: {
            batId: 9983,
            batName: "van Beek",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 6,
            balls: 9,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 66.67,
            outDesc: "not out",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_6: {
            batId: 13272,
            batName: "Edwards",
            batShortName: "",
            isCaptain: true,
            isKeeper: true,
            runs: 15,
            balls: 20,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 75,
            outDesc: "c Iftikhar Ahmed       b Naseem Shah",
            bowlerId: 14247,
            fielderId1: 10799,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_4: {
            batId: 6708,
            batName: "Tom Cooper",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 1,
            balls: 2,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 50,
            outDesc: "c Mohammad Wasim Jr       b Shadab Khan",
            bowlerId: 11186,
            fielderId1: 15040,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "CAUGHT",
          },
          bat_11: {
            batId: 9357,
            batName: "van Meekeren",
            batShortName: "",
            isCaptain: false,
            isKeeper: false,
            runs: 7,
            balls: 7,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 100,
            outDesc: "run out (Shadab Khan/Rizwan) ",
            bowlerId: 0,
            fielderId1: 9468,
            fielderId2: 9468,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "RUNOUT",
          },
        },
      },
      bowlTeamDetails: {
        bowlTeamId: 3,
        bowlTeamName: "Pakistan",
        bowlTeamShortName: "PAK",
        bowlersData: {
          bowl_1: {
            bowlerId: 12160,
            bowlName: "Shaheen Afridi",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 19,
            wickets: 1,
            economy: 4.8,
            no_balls: 0,
            wides: 1,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_4: {
            bowlerId: 14561,
            bowlName: "Haris Rauf",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 3,
            maidens: 0,
            runs: 10,
            wickets: 1,
            economy: 3.3,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_6: {
            bowlerId: 8367,
            bowlName: "Nawaz",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 2,
            maidens: 0,
            runs: 11,
            wickets: 0,
            economy: 5.5,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_5: {
            bowlerId: 11186,
            bowlName: "Shadab Khan",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 22,
            wickets: 3,
            economy: 5.5,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_3: {
            bowlerId: 15040,
            bowlName: "Mohammad Wasim Jr",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 3,
            maidens: 0,
            runs: 15,
            wickets: 2,
            economy: 5,
            no_balls: 0,
            wides: 1,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_2: {
            bowlerId: 14247,
            bowlName: "Naseem Shah",
            bowlShortName: "",
            isCaptain: false,
            isKeeper: false,
            overs: 4,
            maidens: 0,
            runs: 11,
            wickets: 1,
            economy: 2.8,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
        },
      },
      scoreDetails: {
        ballNbr: 120,
        isDeclared: false,
        isFollowOn: false,
        overs: 20,
        revisedOvers: 0,
        runRate: 4.55,
        runs: 91,
        wickets: 9,
        runsPerBall: 0.46,
      },
      extrasData: {
        noBalls: 0,
        total: 5,
        byes: 0,
        penalty: 0,
        wides: 2,
        legByes: 3,
      },
      ppData: {
        pp_1: {
          ppId: 81,
          ppOversFrom: 0.1,
          ppOversTo: 6,
          ppType: "mandatory",
          runsScored: 19,
        },
      },
      wicketsData: {
        wkt_8: {
          batId: 12783,
          batName: "Fred Klaassen",
          wktNbr: 8,
          wktOver: 18.3,
          wktRuns: 81,
          ballNbr: 183,
        },
        wkt_2: {
          batId: 6708,
          batName: "Tom Cooper",
          wktNbr: 2,
          wktOver: 6.1,
          wktRuns: 19,
          ballNbr: 61,
        },
        wkt_9: {
          batId: 9357,
          batName: "van Meekeren",
          wktNbr: 9,
          wktOver: 20,
          wktRuns: 91,
          ballNbr: 200,
        },
        wkt_1: {
          batId: 8073,
          batName: "Myburgh",
          wktNbr: 1,
          wktOver: 2.2,
          wktRuns: 7,
          ballNbr: 22,
        },
        wkt_6: {
          batId: 1669,
          batName: "van der Merwe",
          wktNbr: 6,
          wktOver: 16.3,
          wktRuns: 73,
          ballNbr: 163,
        },
        wkt_4: {
          batId: 9725,
          batName: "Ackermann",
          wktNbr: 4,
          wktOver: 14.2,
          wktRuns: 61,
          ballNbr: 142,
        },
        wkt_5: {
          batId: 13272,
          batName: "Edwards",
          wktNbr: 5,
          wktOver: 15.3,
          wktRuns: 69,
          ballNbr: 153,
        },
        wkt_7: {
          batId: 15205,
          batName: "Tim Pringle",
          wktNbr: 7,
          wktOver: 18.2,
          wktRuns: 81,
          ballNbr: 182,
        },
        wkt_3: {
          batId: 10424,
          batName: "Max ODowd",
          wktNbr: 3,
          wktOver: 8.1,
          wktRuns: 26,
          ballNbr: 81,
        },
      },
      partnershipsData: {
        pat_10: {
          bat1Id: 9983,
          bat1Name: "van Beek",
          bat1Runs: 2,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 9357,
          bat2Name: "van Meekeren",
          bat2Runs: 6,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 9,
          totalBalls: 9,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_1: {
          bat1Id: 8073,
          bat1Name: "Myburgh",
          bat1Runs: 6,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 10424,
          bat2Name: "Max ODowd",
          bat2Runs: 0,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 7,
          totalBalls: 14,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_6: {
          bat1Id: 1669,
          bat1Name: "van der Merwe",
          bat1Runs: 4,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 13272,
          bat2Name: "Edwards",
          bat2Runs: 4,
          bat2fours: 1,
          bat2sixes: 0,
          totalRuns: 8,
          totalBalls: 7,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_9: {
          bat1Id: 9983,
          bat1Name: "van Beek",
          bat1Runs: 0,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 12783,
          bat2Name: "Fred Klaassen",
          bat2Runs: 0,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 0,
          totalBalls: 1,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_2: {
          bat1Id: 13273,
          bat1Name: "Bas de Leede",
          bat1Runs: 6,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 10424,
          bat2Name: "Max ODowd",
          bat2Runs: 5,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 11,
          totalBalls: 21,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_5: {
          bat1Id: 9725,
          bat1Name: "Ackermann",
          bat1Runs: 23,
          bat1fours: 2,
          bat1sixes: 0,
          bat2Id: 13272,
          bat2Name: "Edwards",
          bat2Runs: 11,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 35,
          totalBalls: 37,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_3: {
          bat1Id: 6708,
          bat1Name: "Tom Cooper",
          bat1Runs: 1,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 10424,
          bat2Name: "Max ODowd",
          bat2Runs: 0,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 1,
          totalBalls: 2,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_8: {
          bat1Id: 9983,
          bat1Name: "van Beek",
          bat1Runs: 4,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 15205,
          bat2Name: "Tim Pringle",
          bat2Runs: 2,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 8,
          totalBalls: 11,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_4: {
          bat1Id: 9725,
          bat1Name: "Ackermann",
          bat1Runs: 4,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 10424,
          bat2Name: "Max ODowd",
          bat2Runs: 3,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 7,
          totalBalls: 12,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
        pat_7: {
          bat1Id: 1669,
          bat1Name: "van der Merwe",
          bat1Runs: 1,
          bat1fours: 0,
          bat1sixes: 0,
          bat2Id: 15205,
          bat2Name: "Tim Pringle",
          bat2Runs: 3,
          bat2fours: 0,
          bat2sixes: 0,
          totalRuns: 4,
          totalBalls: 6,
          bat1balls: 0,
          bat2balls: 0,
          bat1Ones: 0,
          bat1Twos: 0,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 0,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 0,
          bat2Sixers: 0,
        },
      },
    },
    {
      matchId: 43126,
      inningsId: 2,
      timeScore: 1667121976000,
      batTeamDetails: {
        batTeamId: 3,
        batTeamName: "Pakistan",
        batTeamShortName: "PAK",
        batsmenData: {
          bat_5: {
            batId: 10799,
            batName: "Iftikhar Ahmed",
            batShortName: "Iftikhar Ahmed",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_2: {
            batId: 8359,
            batName: "Babar Azam",
            batShortName: "Babar Azam",
            isCaptain: true,
            isKeeper: false,
            runs: 4,
            balls: 5,
            dots: 4,
            fours: 1,
            sixes: 0,
            mins: 8,
            strikeRate: 80,
            outDesc: "run out (van der Merwe) ",
            bowlerId: 0,
            fielderId1: 1669,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 1,
            sixers: 0,
            wicketCode: "RUNOUT",
          },
          bat_10: {
            batId: 14561,
            batName: "Haris Rauf",
            batShortName: "Haris Rauf",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_7: {
            batId: 8367,
            batName: "Mohammad Nawaz",
            batShortName: "Nawaz",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_1: {
            batId: 9468,
            batName: "Mohammad Rizwan",
            batShortName: "Rizwan",
            isCaptain: false,
            isKeeper: true,
            runs: 21,
            balls: 19,
            dots: 9,
            fours: 2,
            sixes: 0,
            mins: 25,
            strikeRate: 110.53,
            outDesc: "batting",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 4,
            twos: 3,
            threes: 1,
            fives: 0,
            boundaries: 2,
            sixers: 0,
            wicketCode: "",
          },
          bat_8: {
            batId: 15040,
            batName: "Mohammad Wasim Jr",
            batShortName: "Mohammad Wasim Jr",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_3: {
            batId: 10863,
            batName: "Fakhar Zaman",
            batShortName: "Fakhar Zaman",
            isCaptain: false,
            isKeeper: false,
            runs: 13,
            balls: 11,
            dots: 5,
            fours: 2,
            sixes: 0,
            mins: 11,
            strikeRate: 118.18,
            outDesc: "batting",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 3,
            twos: 1,
            threes: 0,
            fives: 0,
            boundaries: 2,
            sixers: 0,
            wicketCode: "",
          },
          bat_9: {
            batId: 12160,
            batName: "Shaheen Afridi",
            batShortName: "Shaheen Afridi",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_6: {
            batId: 11186,
            batName: "Shadab Khan",
            batShortName: "Shadab Khan",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_4: {
            batId: 9545,
            batName: "Shan Masood",
            batShortName: "Masood",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
          bat_11: {
            batId: 14247,
            batName: "Naseem Shah",
            batShortName: "Naseem Shah",
            isCaptain: false,
            isKeeper: false,
            runs: 0,
            balls: 0,
            dots: 0,
            fours: 0,
            sixes: 0,
            mins: 0,
            strikeRate: 0,
            outDesc: "",
            bowlerId: 0,
            fielderId1: 0,
            fielderId2: 0,
            fielderId3: 0,
            ones: 0,
            twos: 0,
            threes: 0,
            fives: 0,
            boundaries: 0,
            sixers: 0,
            wicketCode: "",
          },
        },
      },
      bowlTeamDetails: {
        bowlTeamId: 24,
        bowlTeamName: "Netherlands",
        bowlTeamShortName: "NED",
        bowlersData: {
          bowl_1: {
            bowlerId: 12783,
            bowlName: "Fred Klaassen",
            bowlShortName: "Fred Klaassen",
            isCaptain: false,
            isKeeper: false,
            overs: 2,
            maidens: 0,
            runs: 21,
            wickets: 0,
            economy: 10.5,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_2: {
            bowlerId: 9357,
            bowlName: "Paul van Meekeren",
            bowlShortName: "van Meekeren",
            isCaptain: false,
            isKeeper: false,
            overs: 2.5,
            maidens: 0,
            runs: 13,
            wickets: 0,
            economy: 4.6,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
          bowl_3: {
            bowlerId: 15121,
            bowlName: "Brandon Glover",
            bowlShortName: "Brandon Glover",
            isCaptain: false,
            isKeeper: false,
            overs: 1,
            maidens: 0,
            runs: 4,
            wickets: 0,
            economy: 4,
            no_balls: 0,
            wides: 0,
            dots: 0,
            balls: 0,
            runsPerBall: 0,
          },
        },
      },
      scoreDetails: {
        ballNbr: 35,
        isDeclared: false,
        isFollowOn: false,
        overs: 5.5,
        revisedOvers: 0,
        runRate: 6.51,
        runs: 38,
        wickets: 1,
        runsPerBall: 0.69,
      },
      extrasData: {
        noBalls: 0,
        total: 0,
        byes: 0,
        penalty: 0,
        wides: 0,
        legByes: 0,
      },
      ppData: {
        pp_1: {
          ppId: 82,
          ppOversFrom: 0.1,
          ppOversTo: 6,
          ppType: "mandatory",
          runsScored: 38,
        },
      },
      wicketsData: {
        wkt_1: {
          batId: 8359,
          batName: "Babar Azam",
          wktNbr: 1,
          wktOver: 2,
          wktRuns: 16,
          ballNbr: 20,
        },
      },
      partnershipsData: {
        pat_1: {
          bat1Id: 9468,
          bat1Name: "Rizwan",
          bat1Runs: 12,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 8359,
          bat2Name: "Babar Azam",
          bat2Runs: 4,
          bat2fours: 1,
          bat2sixes: 0,
          totalRuns: 16,
          totalBalls: 12,
          bat1balls: 7,
          bat2balls: 5,
          bat1Ones: 2,
          bat1Twos: 3,
          bat1Threes: 0,
          bat1Fives: 0,
          bat1Boundaries: 1,
          bat1Sixers: 0,
          bat2Ones: 0,
          bat2Twos: 0,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 1,
          bat2Sixers: 0,
        },
        pat_2: {
          bat1Id: 9468,
          bat1Name: "Rizwan",
          bat1Runs: 9,
          bat1fours: 1,
          bat1sixes: 0,
          bat2Id: 10863,
          bat2Name: "Fakhar Zaman",
          bat2Runs: 13,
          bat2fours: 2,
          bat2sixes: 0,
          totalRuns: 22,
          totalBalls: 23,
          bat1balls: 12,
          bat2balls: 11,
          bat1Ones: 2,
          bat1Twos: 0,
          bat1Threes: 1,
          bat1Fives: 0,
          bat1Boundaries: 1,
          bat1Sixers: 0,
          bat2Ones: 3,
          bat2Twos: 1,
          bat2Threes: 0,
          bat2Fives: 0,
          bat2Boundaries: 2,
          bat2Sixers: 0,
        },
      },
    },
  ],
  matchHeader: {
    matchId: 43126,
    matchDescription: "29th Match, Super 12 Group 2",
    matchFormat: "T20",
    matchType: "International",
    complete: false,
    domestic: false,
    matchStartTimestamp: 1667113200000,
    matchCompleteTimestamp: 1667124000000,
    dayNight: false,
    year: 2022,
    state: "In Progress",
    status: "Netherlands opt to bat",
    tossResults: {
      tossWinnerId: 24,
      tossWinnerName: "Netherlands",
      decision: "Batting",
    },
    result: {
      winningTeam: "",
      winByRuns: false,
      winByInnings: false,
    },
    revisedTarget: {
      reason: "",
    },
    playersOfTheMatch: [],
    playersOfTheSeries: [],
    matchTeamInfo: [
      {
        battingTeamId: 24,
        battingTeamShortName: "NED",
        bowlingTeamId: 3,
        bowlingTeamShortName: "PAK",
      },
      {
        battingTeamId: 3,
        battingTeamShortName: "PAK",
        bowlingTeamId: 24,
        bowlingTeamShortName: "NED",
      },
    ],
    isMatchNotCovered: false,
    team1: {
      id: 3,
      name: "Pakistan",
      playerDetails: [],
      shortName: "PAK",
    },
    team2: {
      id: 24,
      name: "Netherlands",
      playerDetails: [],
      shortName: "NED",
    },
    seriesDesc: "ICC Mens T20 World Cup 2022",
    seriesId: 3961,
    seriesName: "ICC Mens T20 World Cup 2022",
  },
  isMatchComplete: false,
  status: "Pakistan need 54 runs in 85 balls",
  videos: [],
  responseLastUpdated: 1667122024,
};
